### ISSUE TITLE
sphinx.ext.pngmath problem on readthedocs

### ISSUE THREAD

**Issue by aewallin** [aewallin/allantools#94]
the documentation will not build at the moment...

Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/latest/lib/python2.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/latest/lib/python2.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
ExtensionError: Could not import extension sphinx.ext.pngmath (exception: No module named pngmath)

Extension error:
Could not import extension sphinx.ext.pngmath (exception: No module named pngmath)

**Comment by aewallin** [comment]
fix is:
sphinx.ext.imgmath
